stages:
- name: Build and Publish
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: kamil71/${CICD_IMAGE}:${CICD_EXECUTION_SEQUENCE}
      pushRemote: true
      registry: index.docker.io
